dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: mukAyYafHSwg2GKi5U/B9Px0ogbQGzriyGk9HtvRXU97i38fKzlOOzkrBc5SJZmKknvxXEQZpFAx7gHuJlAFz3UY4Lj5KXKJmRcj8oqKEsefOH3MPwptSbb9ft1aeRkLkrnWpgsiyWiJdFnxw3BwbR2fnTYPfiLjfxsQD7QXtwvdSM47an8rez5M6X7TsjSmyC+UoY3FKuEQGl98kWtXd1UZXA1aCXyoXoJBFz7U+ynUKYVHpETlpNlOZJYgDKrx85lySjJs1Nzi8R1QSfgRZwHrwDdRjr7LlcovpRMyIK9G+UwphcqiL0N1FzDSEGqTEPNz/GLHW0zSNSdqC+HyYYHemS3liqHU1y7E8yTeRUY9qwdhnNDoz/MFl/mw7J5TOAxCX/SZ0t4KEgy6N6/QV5exDSzXPw58V53SAhPfGNKlrcBSdNarzj7oUGZv1dPYkAzKDpAXcwNZcVypWThluA+tR7VhjlmIGSPZnjrdI0CJrmBQOEsIjv+t16xTdzFyU/zY4eVaPFhhzi8cwoQju5kvprdq7+XxVgEnxvoORWQ8nYOo1lPYqZeqD6sUWaaSv/5J0NwCwRB6otU+4UbxYR4/vBGodqxXKZJs+A8iUqIYoIKBA6FQGGVu3Q7jmNx5db+quopwDcwYglYYblb48Aedf02dUAhPeAKtBYDqIF0=
  - secure: rKuq5YR91j8W4bBoP3UxJPkJLKNVWcuoyIsIWVw4wjEG5UOCcasUa8f0mkKmfshoA5KNQiO8+1hLZYb8nqQP07BQSNy2T0G5tI0bKM4q0cdxpXfQfvPM5NIGGg1BuH9WVmOwY6y7Ez2gJqqPirO2B1b4/qretN3zkwTc3KzeX9bi2rHJdOBmnxBmC1HrAzn1u7O0AcECKlsgqzMyQL+QO5JpzqKVJ/iTAfMGdEYpBv58sq+2QmGBqxzMdT9G0+d0b1AsbPGtfIHPjScNkNkpJOxq3GHvpPslkXOcI9P/9rsbbaXnKDBj4KJjp3zMTuBHScDXs2IRnfVLDNUPQZt7iIAxRe55cpp5vGwcqdqt9xAdXGGHod0LofGTEE1pyc2P0z0eTFO9gGSyh58DEWToS7WAiRC3lEPZ5XSkAvL1UUs2vXClBCkrXJ7hEM9lESDp6Lu7wEi3x47S6Lsx6QsSTdRljctgOb2qszbfks+9iQs8H883o7wiawk6spbl4FLhV/OplERnG2aiAMPD9i/cX9r5wplwaxetRFYhdukApZflw9CA8S/kOmQzzICqEvplmACAlcGTbc6JAFJLdRDomr8YzqDpfo8OmLHkLo4eDQ9Fr5Bw/lhsR2aymqPtHSzPqQtyx48RU1nWmfp5QvfXTXNmpQwQVcfBNjXNxpAmEHc=
  - secure: H6Iw2snOC6NpCH8CEg91LGZgDfq/ropOcohv6kkmKywgug6XLiYdTdSZuRMjPWKBqlCCs/tTTjUTZUMssbIQzsD/TQt7zwyyxYAdr+wShG0D8Y8hOyROS5rLYNartS5nUMvov9wgNK1j3t6Fr8PZSN54AtOmHHM6BmU3/36NWDHuuE8+8C+WrSb3dtrtkBbMukOR+OIykw/c+E+DkS+Te/bSbBesoyukiseIgbpr8B7LXtzHy1mgQf4WTqy5t+1TbEd6k2+R5yHG1RmahZCRqXgWRs8TMIybfBGteGKuPJmg8rGcHON3y23pZzCIx65Nx00Ilk2bM11V2605t9Kos9O1ZcyCy7no8KcchVbhJHoKwEKghO2Qk5JUNPM6hbH9fr9a9MS23Yj6/d+aOkd7qvH1gkcr06oGzMokXZoVG2YHtvg7GrSFSdF4+LDKjlzW4sE6j4J7mdke4lciyRClMnhOCjRMew54u3G45vgkGPAH6ciZcS+0mOT06xTV8j0OuKbpYT2TuCFYGh0yYH9p1YYDipiLPxlOuSQT9QCKIRJ31ivedArEugOT9VTVkiQypMK+vUh0QwlpLa+xoLiDGrs7txNIn3mRd8CK7FR/n11ucWNAfrgZgKLkFLohaXukpnMRDqdKkNOylGhEJNXO/Lox/XMW9dNNyvQD3E7WnH0=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
